name: auto_localization
description: This is a project to automatically translate your app in any language.
version: 1.2.0
homepage: https://github.com/Sipioteo/auto_localization

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:

  translator: ^0.1.7
  hive: ^2.0.4
  hive_flutter: ^1.1.0


  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

